### ISSUE TITLE
Remake Website

### ISSUE THREAD

**Issue by wisn** [celluloid/celluloid.github.com#7]
Is it possible for me to remake this website?
I will use another framework instead of Bootstrap for the CSS framework.
And also, adding another useful pages?

**Comment by wisn** [comment]
Currently, the website looks like this:
![screenshot from 2016-11-16 08-20-49](https://cloud.githubusercontent.com/assets/8147926/20331066/a34d965a-abd5-11e6-9bdc-8448d2f90dc6.png)

I need your opinion, @tarcieri.

**Comment by tarcieri** [comment]
What browser are you using? It looks like this to me:

![screen shot 2016-11-15 at 5 24 05 pm](https://cloud.githubusercontent.com/assets/797/20331156/680f1ec4-ab58-11e6-8c88-ba37dc7e4fd1.png)

I agree the site could use some work, but would want to see a prospective replacement before deciding on whether or not to replace it.

**Comment by wisn** [comment]
It's on my local PC.
If it's finished, I'll send a PR.

**Comment by tarcieri** [comment]
Something's wrong with your computer/browser then

**Comment by wisn** [comment]
Here is my work on http://www.nurcahyo.me/celluloid.github.com/

**Comment by tarcieri** [comment]
That looks like this to me:

![screen shot 2016-11-15 at 5 36 27 pm](https://cloud.githubusercontent.com/assets/797/20331445/1c29702a-ab5a-11e6-9d17-ad9ddc8dd95d.png)

**Comment by wisn** [comment]
I'll fix the logo.
It's only 15% from my target to rebuild the website.

**Comment by digitalextremist** [comment]
It does seem like a regression. What problem is being solved?

**Comment by wisn** [comment]
It's unfinished.
Before I do a massive work, I would to ask your opinion first.
I'll rebuild Celluloid website and provides online documentation on it.

**Comment by wisn** [comment]
May you check http://www.nurcahyo.me/celluloid.github.com/ again?
I've updated it.

**Comment by dilumn** [comment]
Redesigning & adding all `celluloid` organization repository infos, wikis into http://celluloid.io/ central location can be done as a `GSoC` project next year?

**Comment by wisn** [comment]
Emm...
I don't know what should I say...

**Comment by wisn** [comment]
So, for now, I will send a PR for the homepage.
May I?

**Comment by tarcieri** [comment]
@wisn while I think the site could benefit from the move to a flat design, I'm not sure what you've done is what I have in mind. It seems pretty drab to me.

**Comment by wisn** [comment]
@tarcieri What kind of design did you like?

**Comment by tarcieri** [comment]
For lack of a better description, I find the new version "aesthetically unappealing". I'm not saying the original was great (and gradients have definitely gone "out of style"), but using a framework like Bootstrap gets you a designer's touch "for free" on many of the page elements, which your version seems to be lacking.

I could give you a list of many small issues to fix, but I'm not sure that will really help achieve a good looking result, and I would also hate to have you keep tweaking it only to have it rejected.

**Comment by wisn** [comment]
Please feel free to reject it. So, I'll fix some issue in the current website instead of rebuild it then.

**Comment by tarcieri** [comment]
Personally I'd suggest upgrading to Bootstrap v4, or at the very least mimicking the styles in your current version.

I can leave some comments on your PR.
